language: go
go:
  - 1.9.x
branches:
  only:
  - master
  - dev

before_install:
  - go vet ./...
  - go get github.com/mitchellh/gox

after_success:
  - test $TRAVIS_BRANCH = "dev" && gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" && ls

