#
#  Template usage:
# 
#       This template depends on the LC template and also the VPC stack.
#       This is a NON working template. only for demonstration purposes for cf-doc
#

AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cloudformation Template for AutoScalingGroups (ASG)'
# Testing Parameters
Parameters:
  pLaunchConfigurationName:
    Type: String
    Description: Launch configuration name
  pVPCZoneIdentifier:
    Type: CommaDelimitedList
    Description: Subnets List of VPC

Conditions:
  LoadBalancerNamesNull: !Equals 
    - !Join
      - ''
      - !Ref pLoadBalancerNames
    - ''

Resources:
  asg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref 'pLaunchConfigurationName'
      VPCZoneIdentifier: !Ref 'pVPCZoneIdentifier'
      Cooldown: !Ref 'pCooldown'
      MinSize: !Ref 'pMinSize'
      MaxSize: !Ref 'pMaxSize'
      DesiredCapacity: !Ref 'pDesiredCapacity'
      HealthCheckGracePeriod: !Ref 'pHealthCheckGracePeriod'
      HealthCheckType: !Ref 'pHealthCheckType'
      Tags:
      - Key: Name
        Value: ''
        PropagateAtLaunch: true

Outputs:
  asgid:
    Description: AsgBase Logical ID
    Value: !Ref 'asg'
    Export:
      Name: !Sub "${AWS::StackName}-asgid"
